title: Olli
email: joseph@josephbanks.me
description: Olli searches your Loki logs and relays matching terms to Discord.
baseurl: "/olli/"
url: ""
twitter_username: PythonDiscord
github_username:  python-discord

remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-remote-theme

color_scheme: light

aux_links:
  "Olli on GitHub":
    - "https://github.com/python-discord/olli"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/python-discord/olli"
gh_edit_source: docs
gh_edit_branch: "main"
gh_edit_view_mode: "tree"
